param([string]$MeleeRoot = (Join-Path $PSScriptRoot '..\..\work\melee-base'))
$ErrorActionPreference = 'Stop'
$mtxSource = Join-Path $MeleeRoot 'libs\dolphin\include\dolphin\mtx.h'
$mtxHeader = [IO.File]::ReadAllText($mtxSource)
$mtxHeader += "`r`n#ifdef __cplusplus`r`nextern `"C`" {`r`n#endif`r`nvoid PSMTXTrans(Mtx m, f32 x, f32 y, f32 z);`r`n#ifdef __cplusplus`r`n}`r`n#endif`r`n"
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'compat\dolphin\mtx.h'),"/* Generated original declarations plus missing PSMTXTrans prototype. */`r`n"+$mtxHeader)
$source = Join-Path $MeleeRoot 'src\melee\mn\types.h'
$text = [IO.File]::ReadAllText($source)
$start = $text.IndexOf('struct StartMeleeRules {')
$end = $text.IndexOf('    u8 x6;', $start)
if ($start -lt 0 -or $end -le $start) { throw 'StartMeleeRules source boundary changed.' }
$flags = $text.Substring($start, $end-$start)
$fields = [regex]::Matches($flags, 'u32 (\w+) : (\d+);')
$bits = 0
foreach ($field in $fields) { $bits += [int]$field.Groups[2].Value }
if ($fields.Count -ne 44 -or $bits -ne 48) { throw 'StartMeleeRules flags changed; review the adapter.' }
$flags = [regex]::Replace($flags, 'u32 (\w+) : (\d+);', 'u8 $1 : $2;')
$adapted = $text.Substring(0,$start) + $flags + $text.Substring($end)
$preamble = "/* Generated by generate-compat-headers.ps1 from unchanged upstream mn/types.h.`r`n * Xbox bitfield storage is rounded to the declared base type. These six`r`n * flag bytes use u8 storage to preserve the GameCube field offsets.`r`n * Source SHA256: $((Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash) */`r`n"
$destination = Join-Path $PSScriptRoot 'compat\melee\mn\types.h'
New-Item -ItemType Directory -Force (Split-Path $destination) | Out-Null
[IO.File]::WriteAllText($destination, $preamble + $adapted)
Write-Output 'Generated isolated StartMeleeRules bitfield adapter (48 bits in six bytes).'
$gameplayIncludes = @('#include <melee/ft/forward.h>')
foreach ($relative in @(Get-ChildItem (Join-Path $MeleeRoot 'src\melee\ft') -Recurse -Filter '*.h' | Where-Object { [IO.File]::ReadAllText($_.FullName) -match 'static MotionFlags const' } | ForEach-Object { $_.FullName.Substring((Resolve-Path (Join-Path $MeleeRoot 'src')).Path.Length+1) })) {
    $original = Join-Path $MeleeRoot "src\$relative"
    $header = [IO.File]::ReadAllText($original)
    # MSVC C does not accept const variables as static initializer constants.
    # These flags have no storage/address consumers; preserve expressions as macros.
    $header = [regex]::Replace($header, 'static MotionFlags const (\w+)\s*=\s*([^;]+);', {
        param($match)
        '#define '+$match.Groups[1].Value+' ((MotionFlags) ('+([regex]::Replace($match.Groups[2].Value,'\s+',' '))+'))'
    })
    $target = Join-Path $PSScriptRoot "compat\$relative"
    New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
    [IO.File]::WriteAllText($target, "/* Generated XDK C constant-expression adapter. Source SHA256: $((Get-FileHash -LiteralPath $original).Hash) */`r`n"+$header)
    if ($relative -ne 'melee\ft\forward.h') { $gameplayIncludes += '#include <'+$relative.Replace('\','/')+'>' }
}
$gameplayIncludes += '#include <melee/ft/types.h>'
New-Item -ItemType Directory -Force (Join-Path $PSScriptRoot 'compat\generated') | Out-Null
$gameplayIncludes | Set-Content (Join-Path $PSScriptRoot 'compat\generated\gameplay_headers.h')
$cardSource = Join-Path $MeleeRoot 'src\melee\lb\lbcardnew.h'
$fighterSource = Join-Path $MeleeRoot 'src\melee\ft\types.h'
$fighterHeader = [IO.File]::ReadAllText($fighterSource)
$oldField = '/* fp+596:0 */ u8 x0 : 7;'
if (!$fighterHeader.Contains($oldField)) { throw 'Fighter x596 bitfield boundary changed.' }
$fighterHeader = $fighterHeader.Replace($oldField,'/* fp+596:0 */ u16 x0 : 7;')
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'compat\melee\ft\types.h'), "/* Generated: use one 16-bit bitfield allocation for x596. All original size assertions retained. Source SHA256: $((Get-FileHash $fighterSource).Hash) */`r`n"+$fighterHeader)
$cardHeader = [IO.File]::ReadAllText($cardSource)
foreach($name in @('lb_8001B8C8','lb_8001BA44')) {
    $cardHeader = $cardHeader.Replace("bool $name(","int $name(")
}
$cardTarget = Join-Path $PSScriptRoot 'compat\melee\lb\lbcardnew.h'
New-Item -ItemType Directory -Force (Split-Path $cardTarget) | Out-Null
[IO.File]::WriteAllText($cardTarget,"/* Generated: return types match original C definitions; bool fields stay one byte. */`r`n"+$cardHeader)
