from pathlib import Path
import hashlib,json,re
root=Path(__file__).resolve().parents[1]
base=root.parents[1]/'work/melee-base'
src=base/'src/melee/lb/lbmemory.c'
s=src.read_text()
s=s.replace('#include "lbmemory.h"','#include <melee/lb/lbmemory.h>')
s=s.replace('(uintptr_t) arenaLo < 0x80000000U && (uintptr_t) arenaHi < 0x80000000U','(uintptr_t) arenaLo < ARGetSize() && (uintptr_t) arenaHi <= ARGetSize()')
s=s.replace('(uintptr_t) block->addr < 0x80000000U','(uintptr_t) block->addr < ARGetSize()')
(root/'compat/generated/portable_lbmemory.c').write_text(s)
(root/'logs/bootstrap-memory-provenance.json').write_text(json.dumps({'source':str(src),'sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'adaptations':['quoted include qualified','ARAM identification uses actual ARGetSize, not GameCube 0x80000000 RAM boundary'],'originalPreserved':True},indent=2))

# Copy exact original bodies; no missing-function substitutes.
manifest=[]
for relative,start,end,target,prefix in [
 ('src/melee/lb/lbarchive.c','void lbArchive_InitializeDAT(','static inline void vLoadSections','original_archive_init.c','#include "../compat/gameplay_boundary.h"\n#include <melee/lb/lbarchive.h>\n#include <sysdolphin/baselib/archive.h>\n#include <sysdolphin/baselib/debug.h>\n'),
 ('src/sysdolphin/baselib/synth.c','void* HSD_AudioMalloc(','static int HSD_Synth_804D6028','original_audio_alloc.c','#include "../compat/gameplay_boundary.h"\n#include <dolphin/os/OSAlloc.h>\n#include <sysdolphin/baselib/debug.h>\nOSHeapHandle HSD_Synth_804D6018 = -1;\n')]:
 source=base/relative;original=source.read_text();body=original[original.index(start):original.index(end)]
 (root/'src'/target).write_text(prefix+'/* Exact original bodies; generated by generate_bootstrap_memory.py. */\n'+body)
 manifest.append({'source':relative,'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'output':target,'body':'unchanged','originalPreserved':True})
(root/'logs/bootstrap-original-bodies.json').write_text(json.dumps(manifest,indent=2))

# GameCube linker alignment must be explicit for the XDK DVD DMA contract.
devcom=(base/'src/sysdolphin/baselib/devcom.c').read_text()
devcom=re.sub(r'#include "([^"\n]+)"',lambda m:'#include <sysdolphin/baselib/'+m.group(1)+'>',devcom)
devcom=devcom.replace('static int HSD_DevCom_804C6330_bufs','__declspec(align(32)) static int HSD_DevCom_804C6330_bufs')
devcom=devcom.replace('    HSD_ASSERT(0x1F0, dest % 32 == 0);','    if(dest % 32) OSReport("DevCom unaligned destination: file=%d type=%x src=%x dest=%x bytes=%u\\n",file,type,(unsigned)src,(unsigned)dest,(unsigned)size);\n    HSD_ASSERT(0x1F0, dest % 32 == 0);')
(root/'compat/generated/native').mkdir(exist_ok=True)
(root/'compat/generated/native/devcom.c').write_text(devcom)


