#include "../compat/gameplay_boundary.h"
#include <dolphin/os/OSAlloc.h>
#include <sysdolphin/baselib/debug.h>
OSHeapHandle HSD_Synth_804D6018 = -1;
/* Exact original bodies; generated by generate_bootstrap_memory.py. */
void* HSD_AudioMalloc(size_t size)
{
    void* p = OSAllocFromHeap(HSD_Synth_804D6018, size);
    HSD_ASSERTREPORT(0x29U, p, "audio heap overflow.\n");
    return p;
}

void HSD_AudioFree(void* ptr)
{
    OSFreeToHeap(HSD_Synth_804D6018, ptr);
}

