#include "../compat/gameplay_boundary.h"
#include <melee/lb/lbarchive.h>
#include <sysdolphin/baselib/archive.h>
#include <sysdolphin/baselib/debug.h>
/* Exact original bodies; generated by generate_bootstrap_memory.py. */
void lbArchive_InitializeDAT(HSD_Archive* archive, void* data, size_t length)
{
    const char* symbol;
    int i = 0;

    if (HSD_ArchiveParse(archive, data, length) == -1) {
        OSReport("HSD_ArchiveParse error!\n");
        HSD_ASSERT(73, 0);
    }

    while (true) {
        symbol = HSD_ArchiveGetExtern(archive, i++);
        if (symbol != NULL) {
            HSD_ArchiveLocateExtern(archive, symbol, NULL);
        }
        if (symbol == NULL) {
            return;
        }
    }
}

