#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E PSCheck /Vn Melee360XfbPSCheck /Fh
//    C:\Users\luizf\Documents\Codex\2026-10-01\referenced-chatgpt-conversation-this-is-an-2\outputs\Melee360\src\xfb_PSCheck.h
//    C:\Users\luizf\Documents\Codex\2026-10-01\referenced-chatgpt-conversation-this-is-an-2\outputs\Melee360\src\xfb_filter.hlsl
//
//
// Parameters:
//
//   float4 Destination;
//   float4 Expected;
//   float4 Field;
//   float4 Limits;
//   float4 SourceRect;
//   float4 Weights;
//   sampler2D previous;
//   sampler2D source;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   SourceRect   c0       1
//   Destination  c1       1
//   Weights      c2       1
//   Limits       c3       1
//   Field        c4       1
//   Expected     c5       1
//   source       s0       1
//   previous     s1       1
//

// Shader type: pixel 

xps_3_0
defconst Destination, float, vector, [1, 4], c1
defconst Expected, float, vector, [1, 4], c5
defconst Field, float, vector, [1, 4], c4
defconst Limits, float, vector, [1, 4], c3
defconst SourceRect, float, vector, [1, 4], c0
defconst Weights, float, vector, [1, 4], c2
defconst previous, sampler2d, object, [1, 1], s1
defconst source, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=5
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy

def c248, 0, 0, 0, 0
def c249, 0, 0, 0, 0
def c250, 0, 0, 0, 0
def c251, 0, 0.015625, 32, -2
def c252, 512, 255, 0.00392156886, 1
def c253, -1, 0.5, 0.25, 0.0625
def c254, 8, 4, 0.125, 0.25
def c255, 0.001953125, 0, 0, 0


    exec
    mul r2.x, r0.x, c1.x
  + rcp r1.z, c4.w
    sgt r1.w, c4.x, c253.y
    mad r0.y, r0.y, c251.z, c1.z
    floor r0.z, r0.y
  + rcp r1.y, c0.z
    mul r0.w, c4.z, c1.x
  + mulsc r1.x, c253.y, r0.z
    floor r1.x, r1.x
  + movs r0._, r2.x
    exec    // PredicateClean=false
    mad r0.z, r1.x, c251.w, r0.z
    sne r0.z, r0.z, c4.y
  + muls_prev r1.x, r1.y
    mul r0.z, r1.w, r0.z
  + movs r0._, r0.y
    setp_eq_push r2.x, c251.x, r0.z
  + muls_prev r1.z, r1.z
    (p0) mul r0.z, r0.w, r0.x
  + (p0) rcp r0.x, c1.x
    (p0) mul r0.x, r0.z, r0.x
  + (p0) mulsc r0.z, c1.w, r0.y
(p0) exec
    (p0) add r0.xy, r0.xz, c0.xy
    (p0) floor r0.zw, r0.yyyx
    (p0) add r2.yz, r0.zzw, c253.xxy
    (p0) max r0.x, r2.y, c3.x
    (p0) min r0.x, r0.x, c3.y
    (p0) add r2.w, r0.x, c253.y
  + (p0) rcp r1.w, c0.w
(p0) exec
    (p0) mul r0.xy, r2.zw, r1.yw
    (p0) tfetch2D r2._xyz, r0.xy, tf0, UseComputedLOD=false
    serialize
    (p0) mov_sat r2.yzw, r2.yyzw
    (p0) mad r2.yzw, r2.wwzy, c252.y, c253.y
    (p0) floor r1.x, r2.y
  + (p0) floors r2.y, r2.w
    (p0) sgt r1.z, c3.w, c253.y
  + (p0) floors r0.x, r2.z
    exec    // PredicateClean=false
    setp_ne_push r2.x, r2.x, r1.z
    (p0) mulsc r3.x, c254.z, r1.x
    (p0) mul r3.z, r2.y, c254.z
  + (p0) mulsc r3.y, c254.w, r0.x
    (p0) floor r2.yzw, r3.xxyz
    (p0) mul r3.xyz, r2.yzw, c254.xyx
    (p0) mul r2.yzw, r2.wwzy, c253.zzwz
    exec    // PredicateClean=false
    (p0) floor r2.yzw, r2.zzwy
    (p0) add r0.x, r3.y, r2.y
  + (p0) movs r0._, r3.x
    (p0) add r2.y, r3.z, r2.w
  + (p0) adds_prev r1.x, r2.z
    setp_pop r2.x, r2.x
    (p0) max r0.y, r0.z, c3.x
    (p0) min r0.y, r0.y, c3.y
(p0) exec
    (p0) add r2.w, r0.y, c253.y
  + (p0) addsc r2.z, c253.y, r0.w
    (p0) mul r3.xy, r2.zw, r1.yw
    (p0) tfetch2D r4.xyz_, r3.xy, tf0, UseComputedLOD=false
    serialize
    (p0) mov_sat r4.xyz, r4.xyz
    (p0) mad r4.xyz, r4.zyx, c252.y, c253.y
    (p0) floors r1.y, r4.x
    exec    // PredicateClean=false
    (p0) floor r2.z, r4.z
  + (p0) floors r0.y, r4.y
    setp_ne_push r2.x, r2.x, r1.z
    (p0) mulsc r4.x, c254.z, r1.y
    (p0) mul r4.z, r2.z, c254.z
  + (p0) mulsc r4.y, c254.w, r0.y
    (p0) floor r4.xyz, r4.xyz
    (p0) mul r5.xyz, r4.xyz, c254.xyx
    exec    // PredicateClean=false
    (p0) mul r4.xyz, r4.zyx, c253.zwz
    (p0) floor r4.xyz, r4.zyx
    (p0) add r0.y, r5.y, r4.y
  + (p0) movs r0._, r5.x
    (p0) add r2.z, r5.z, r4.z
  + (p0) adds_prev r1.y, r4.x
    setp_pop r2.x, r2.x
    (p0) addsc r0.z, c252.w, r0.z
(p0) exec
    (p0) max r0.z, r0.z, c3.x
    (p0) min r0.z, r0.z, c3.y
    (p0) addsc r0.z, c253.y, r0.z
    (p0) mul r3.y, r0.z, r1.w
    (p0) tfetch2D r3.xyz_, r3.xy, tf0, UseComputedLOD=false
    serialize
    (p0) mov_sat r3.xyz, r3.xyz
    exec    // PredicateClean=false
    (p0) mad r3.xyz, r3.zyx, c252.y, c253.y
    (p0) floors r1.w, r3.x
    (p0) floor r2.w, r3.z
  + (p0) floors r0.z, r3.y
    setp_ne_push r2.x, r2.x, r1.z
    (p0) mulsc r3.x, c254.z, r1.w
    (p0) mul r3.z, r2.w, c254.z
  + (p0) mulsc r3.y, c254.w, r0.z
(p0) exec
    (p0) floor r3.xyz, r3.xyz
    (p0) mul r4.xyz, r3.xyz, c254.xyx
    (p0) mul r3.xyz, r3.zyx, c253.zwz
    (p0) floor r3.xyz, r3.zyx
    (p0) add r0.z, r4.y, r3.y
  + (p0) movs r0._, r4.x
    (p0) add r2.w, r4.z, r3.z
  + (p0) adds_prev r1.w, r3.x
    exec    // PredicateClean=false
    setp_pop r2.x, r2.x
    (p0) dp3 r1.x, r1.wxy, c2.zxy
    (p0) dp3 r1.y, r0.zxy, c2.zxy
    (p0) dp3 r1.z, r2.wyz, c2.zxy
    (p0) mul r0.xyz, r1.xyz, c251.y
    (p0) floor r0.xyz, r0.xyz
(p0) exec
    (p0) mul r1.xyz, r0.xyz, c255.x
    (p0) floor r1.xyz, r1.xyz
    (p0) mad r0.xyz, -r1.xyz, c252.x, r0.xyz
    (p0) min r0.xyz, r0.xyz, c252.y
    (p0) mul r0.xyz, r0.zyx, c252.z
    (p0) log r0.x, r0_abs.x
(p0) exec
    (p0) log r0.y, r0_abs.y
    (p0) log r0.z, r0_abs.z
    (p0) mul r0.xyz, r0.xyz, c2.w
    (p0) exp r0.x, r0.x
    (p0) exp r0.y, r0.y
    (p0) exp r0.z, r0.z
    exec    // PredicateClean=false
    (p0) mad r0.xyz, r0.zyx, c252.y, c253.y
    (p0) floor r0.xyz, r0.xyz
    (p0) mul r0.xyz, r0.zyx, c252.z
    setp_inv r2.x, r2.x
    (p0) tfetch2D r0.xyz_, r1.xz, tf1, UseComputedLOD=false
    alloc colors
    exece
    mad r0.xyz, r0.xyz, c252.y, -c5.xyz
    maxs r0.w, r0_abs.xy
    max r0.x, r0.w, r0_abs.z
    subsc r0.x, c5.w, r0.x
    kill_gt r0._, c251.x, r0.x
    movs oC0.x111, c252.w

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD Melee360XfbPSCheck[] =
{
    0x102a1100, 0x000001ac, 0x000005b4, 0x00000000, 0x00000024, 0x00000160, 
    0x00000188, 0x00000000, 0x00000000, 0x00000138, 0x0000001c, 0x0000012a, 
    0xffff0300, 0x00000008, 0x0000001c, 0x00000000, 0x00000123, 0x000000bc, 
    0x00020001, 0x00010000, 0x000000c8, 0x00000000, 0x000000d8, 0x00020005, 
    0x00010000, 0x000000c8, 0x00000000, 0x000000e1, 0x00020004, 0x00010000, 
    0x000000c8, 0x00000000, 0x000000e7, 0x00020003, 0x00010000, 0x000000c8, 
    0x00000000, 0x000000ee, 0x00020000, 0x00010000, 0x000000c8, 0x00000000, 
    0x000000f9, 0x00020002, 0x00010000, 0x000000c8, 0x00000000, 0x00000101, 
    0x00030001, 0x00010000, 0x0000010c, 0x00000000, 0x0000011c, 0x00030000, 
    0x00010000, 0x0000010c, 0x00000000, 0x44657374, 0x696e6174, 0x696f6e00, 
    0x00010003, 0x00010004, 0x00010000, 0x00000000, 0x45787065, 0x63746564, 
    0x00466965, 0x6c64004c, 0x696d6974, 0x7300536f, 0x75726365, 0x52656374, 
    0x00576569, 0x67687473, 0x00707265, 0x76696f75, 0x7300abab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x736f7572, 0x63650070, 0x735f335f, 
    0x3000322e, 0x302e3231, 0x3235362e, 0x3000abab, 0x00000000, 0x00000003, 
    0x00000000, 0x00000000, 0x00000014, 0x01f80020, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000080, 0x00000534, 0x10000500, 0x00000004, 
    0x00000000, 0x00000821, 0x00010001, 0x00000021, 0x00003050, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x3c800000, 0x42000000, 0xc0000000, 0x44000000, 0x437f0000, 0x3b808081, 
    0x3f800000, 0xbf800000, 0x3f000000, 0x3e800000, 0x3d800000, 0x41000000, 
    0x40800000, 0x3e000000, 0x3e800000, 0x3b000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00006009, 0x600f1200, 0x10000000, 0x00006015, 0x601b5600, 
    0x56000024, 0x00006021, 0x60271000, 0x10000000, 0x0090602d, 0x60335600, 
    0x10000000, 0x00006039, 0x603f1000, 0x56000900, 0x00006045, 0x604b1000, 
    0x56000000, 0x00006051, 0x60571000, 0x56000000, 0x0000605d, 0x50635600, 
    0x10000100, 0x00000000, 0x6068c400, 0x22000000, 0x4c410102, 0x006c6c1b, 
    0x81000104, 0xc8080001, 0x006cb100, 0x2504fd00, 0xc8020000, 0x00b1c6c6, 
    0x8b00fb01, 0x4c240100, 0x00b100c6, 0xca000000, 0xa8180100, 0x00c66c82, 
    0x010401fd, 0x14010001, 0x006c006c, 0xea010002, 0xc8040000, 0x006c1bc6, 
    0xab01fb00, 0x0c140100, 0x00c6b1b1, 0xa7000401, 0x14040000, 0x001bc6b1, 
    0xe1010000, 0x0c410102, 0x006cc6c6, 0x74fb0001, 0x4c140000, 0x181b6c6c, 
    0xc1000001, 0xa8410000, 0x18c66c01, 0xc1000001, 0xc8030000, 0x18c4b000, 
    0xa0000000, 0xc80c0000, 0x18710000, 0xea000000, 0xc8060002, 0x1816bc00, 
    0xa000fd00, 0xc8010000, 0x18b16c00, 0xa2020300, 0xc8010000, 0x186cb100, 
    0xa3000300, 0x4c880102, 0x186cb11b, 0x8000fd00, 0xc8030000, 0x181a1900, 
    0xe1020100, 0x10082001, 0x8f1ff447, 0x80004000, 0xc90e0002, 0x18010100, 
    0xe2020200, 0xc80e0002, 0x188bb1b1, 0x8b02fcfd, 0x34210201, 0x18b1001b, 
    0xea020002, 0x34140001, 0x181bb1c6, 0x2503fd02, 0xc8010002, 0x006cc600, 
    0xf5020100, 0xac100300, 0x180000c0, 0xc20000fe, 0xa8240303, 0x18b1c600, 
    0x8102fefe, 0xc80e0002, 0x18fc0000, 0xea030000, 0xc8070003, 0x18156000, 
    0xa102fe00, 0xc80e0002, 0x188bd600, 0xa102fd00, 0xc80e0002, 0x18960000, 
    0xea020000, 0x14010000, 0x18b1b16c, 0xe0030203, 0x04120102, 0x18c61bc6, 
    0xe0030202, 0x80100200, 0x0000006c, 0xe2000002, 0xc8020000, 0x18c66c00, 
    0xa2000300, 0xc8020000, 0x18b1b100, 0xa3000300, 0xb0480202, 0x18b1b183, 
    0x8000fdfd, 0xc8030003, 0x181a1900, 0xe1020100, 0x10084061, 0x8f1ffe88, 
    0x80004000, 0xc9070004, 0x18c0c000, 0xe2040400, 0xc8070004, 0x1862b1b1, 
    0x8b04fcfd, 0x34200100, 0x1800006c, 0xe2000004, 0x34240002, 0x18c600b1, 
    0xea040004, 0xc8010002, 0x006cc600, 0xf5020100, 0xac100400, 0x180000c1, 
    0xc20000fe, 0xa8240404, 0x18c6c601, 0x8102fefe, 0xc8070004, 0x18c00000, 
    0xea040000, 0xc8070005, 0x18c06000, 0xa104fe00, 0xc8070004, 0x1862ca00, 
    0xa104fd00, 0xc8070004, 0x18620000, 0xea040000, 0x14020000, 0x18b1b16c, 
    0xe0050405, 0x04240102, 0x18c6c66c, 0xe0050404, 0x80100200, 0x0000006c, 
    0xe2000002, 0xb0400000, 0x18000002, 0xc20000fc, 0xc8040000, 0x18c66c00, 
    0xa2000300, 0xc8040000, 0x18c6b100, 0xa3000300, 0xb0400000, 0x18000082, 
    0xc20000fd, 0xc8020003, 0x18c61b00, 0xe1000100, 0x10083061, 0x8f1ffe88, 
    0x80004000, 0xc9070003, 0x18c0c000, 0xe2030300, 0xc8070003, 0x1862b1b1, 
    0x8b03fcfd, 0x34800100, 0x1800006c, 0xe2000003, 0x34480002, 0x18c600b1, 
    0xea030003, 0xc8010002, 0x006cc600, 0xf5020100, 0xac100300, 0x180000c3, 
    0xc20000fe, 0xa8240303, 0x181bc602, 0x8102fefe, 0xc8070003, 0x18c00000, 
    0xea030000, 0xc8070004, 0x18c06000, 0xa103fe00, 0xc8070003, 0x1862ca00, 
    0xa103fd00, 0xc8070003, 0x18620000, 0xea030000, 0x14040000, 0x18b1b16c, 
    0xe0040304, 0x04880102, 0x18c6c66c, 0xe0040303, 0x80100200, 0x0000006c, 
    0xe2000002, 0xc8010001, 0x18bfbe00, 0xb0010200, 0xc8020001, 0x18bebe00, 
    0xb0000200, 0xc8040001, 0x18c3be00, 0xb0020200, 0xc8070000, 0x18c0b100, 
    0xa101fb00, 0xc8070000, 0x18c00000, 0xea000000, 0xc8070001, 0x18c06c00, 
    0xa100ff00, 0xc8070001, 0x18c00000, 0xea010000, 0xc8070000, 0x1cc06cc0, 
    0xab01fc00, 0xc8070000, 0x18c0b100, 0xa300fc00, 0xc8070000, 0x1862c600, 
    0xa100fc00, 0x40100000, 0x1800006c, 0xe2000080, 0x40200000, 0x180000b1, 
    0xe2000080, 0x40400000, 0x180000c6, 0xe2000080, 0xc8070000, 0x18c01b00, 
    0xa1000200, 0x38100000, 0x1800006c, 0xe2000000, 0x38200000, 0x180000b1, 
    0xe2000000, 0x38400000, 0x180000c6, 0xe2000000, 0xc8070000, 0x1862b1b1, 
    0x8b00fcfd, 0xc8070000, 0x18c00000, 0xea000000, 0xc8070000, 0x1862c600, 
    0xa100fc00, 0x7c100200, 0x0000006c, 0xe2000002, 0x20180021, 0x8f1ffe88, 
    0x80004000, 0xc8070000, 0x01c0b1c0, 0x8b00fc05, 0x14800000, 0x00000061, 
    0xe2000080, 0xc8010000, 0x001bc600, 0xe2008000, 0xb8100000, 0x00000000, 
    0xc2000005, 0xc8000000, 0x006c6c00, 0x79fb0000, 0x14fec000, 0x0000001b, 
    0xc20000fc, 0x00000000, 0x00000000, 0x00000000
};
