#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E PSWhite /Vn Melee360XfbPSWhite /Fh
//    C:\Users\luizf\Documents\Codex\2026-10-01\referenced-chatgpt-conversation-this-is-an-2\outputs\Melee360\src\xfb_PSWhite.h
//    C:\Users\luizf\Documents\Codex\2026-10-01\referenced-chatgpt-conversation-this-is-an-2\outputs\Melee360\src\xfb_filter.hlsl
//
// Shader type: pixel 

xps_3_0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy

def c252, 0, 0, 0, 0
def c253, 0, 0, 0, 0
def c254, 0, 0, 0, 0
def c255, 1, 0, 0, 0


    alloc colors
    exece
    movs oC0.x111, c255.x

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD Melee360XfbPSWhite[] =
{
    0x102a1100, 0x000000a4, 0x00000064, 0x00000000, 0x00000024, 0x00000058, 
    0x00000080, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xffff0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x70735f33, 
    0x5f300032, 0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 0x00000001, 
    0x00000000, 0x00000000, 0x00000014, 0x01fc0010, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000040, 0x00000024, 0x10000000, 0x00000004, 
    0x00000000, 0x00000821, 0x00010001, 0x00000001, 0x00003050, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x3f800000, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x1001c400, 0x22000000, 
    0x14fec000, 0x0000006c, 0xc20000ff, 0x00000000, 0x00000000, 0x00000000
};
